JCROM_VERSION_MAJOR = 3
JCROM_VERSION_MINOR = 0
JCROM_VERSION_MAINTENANCE = 1

JCROM_VERSION := JCROM-$(JCROM_VERSION_MAJOR).$(JCROM_VERSION_MINOR).$(JCROM_VERSION_MAINTENANCE)-$(shell LANG=en date -u +%Y%m%d)


